# Generated by Django 5.1.2 on 2024-10-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ngo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo'),
            preserve_default=False,
        ),
    ]
