# Generated by Django 5.1.2 on 2024-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='username',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='web_links',
        ),
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='contact_person',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
