# Generated by Django 5.0.7 on 2024-12-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0002_remove_ngo_created_at_remove_ngo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='completed_project',
            field=models.CharField(default='No Completed Projects', max_length=255),
        ),
        migrations.AddField(
            model_name='ngo',
            name='ongoing_project',
            field=models.CharField(default='Not Applicable', max_length=255),
        ),
    ]
