# Generated by Django 5.1.2 on 2024-12-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donation_ngo_remove_donation_user_and_more'),
        ('ngos', '0006_ngo_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo'),
        ),
    ]
