# Generated by Django 5.0.6 on 2024-12-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_ngo_id'),
        ('ngos', '0006_ngo_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='ngos.ngo'),
        ),
    ]
